### ISSUE TITLE
关于项目更新问题

### ISSUE THREAD

**Issue by yangjianyao** [WeBankBlockchain/WeIdentity-Sample#55]
最近在学习区块链开发，发现这个sample用的合约的版本好像是v1的，很多新的不支持，我想问下你们有没有计划更新这个sample，比如weid-java-sdk，web3sdk等版本的更新，我尝试了更新这些jar，但是由于自身对这些不熟悉，一直没进展。

**Comment by yanggang-JV** [comment]
目前已维持最新可用状态，欢迎继续体验。
